Erweitern für Gas und Strom
symcon/WasserAlarm pull request #12
Opened 2021-11-22 13:24 UTC by Sunnyka98

Modul wurde für Gas und Strom erweitert, sowie veraltete Elemente des Konfigurationsformular ersetzt.
Die Erweiterung beinhaltet ein Dropdown-Menü zur Auswahl, welches automatisch Profile für die Grenzwerte setzt. Zudem wurde eine Alarmvariable hinzugefügt, welche auslöst sobald entweder die boolsche Variable für Großverbraucher auf true steht oder die Variable für Kleinverbraucher einen vorher festgelegten Wert überschreitet. Auch wurde das Modul in einen verbraucherunabhängigen Zustand umbenannt, sodass es nicht mehr WasserAlarm, sondern VerbraucherAlarm heißt.

[Modules/issues/203](https://github.com/symcon/modules/issues/203)

2022-01-04 14:29 UTC, paresy requested changes
Bitte das Modul komplett neu in einem VerbrauchsAlarm Repo erstellen. Die notwendigen Änderungen, dass wir dies abwärtskompatibel bekommen wären viel zu groß. Den Stress können wir uns sparen und machen es einfach neu.

Sorry, für die lange Zeit bis zum Review!

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/module.php
> -        $this->RegisterPropertyInteger('PipeBurstInterval', 5);
Der Kommentar ist nicht mehr wichtig, da wir einfach ein neues Modul machen. Hier aber kurz die Erklärung, warum wir ein neues Modul machen, damit wir die Kopfschmerzen bzgl. Abwärtskompatibilität nicht haben.

Das geht leider nicht, da wir berücksichtigen müssen, dass Bestandskunden das Modul ja weiterhin haben können und ein "Upgrade" auf die neue Version machen. Hier könnten wir entweder die alte Property behalten und einen Kommentar machen, dass der Name aus Legacygründen nicht geändert wurde, oder wir kopieren den Wert von PipeBurstInterval nach BurstInterval in einem einmaligen "Upgrade" Schritt (coolere Option). Das funktioniert am besten, indem du in ApplyChanges prüfst, ob der PipeBurstInterval >= 0 ist und wenn ja, dann ein Upgrade durchführst mit SetProperty + ApplyChanges. Dabei jedoch PipeBurstInterval dann auf z.B. -1 setzen, damit es nicht ein zweites mal übertragen wird.

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/module.php
> +        $this->RegisterPropertyInteger('flowType', TYPE_WATER);
FlowType

2022-01-04 14:29 UTC, paresy commented on README.md
>  - __Wasser-Alarm__ ([Dokumentation](WasserAlarm))
Noch anpassen

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/form.json
> +			"name": "flowType",
FlowType

Und -> Warum ist FlowType überhaupt definiert, wenn es nie genutzt wird? Fehlt da noch was?

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/README.md
> +# VerbraucherAlarm
VerbraucherAlarm -> VerbrauchsAlarm

Bitte auch Ordner ect. anpassen.

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/README.md
> +Durchflussart            | __Standard: Wasser__ Art, welches Medium fließt.
Durchfluss ist sehr auf Wasser gemünzt. Eher Verbrauchsart?

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/README.md
> +WAA.LeakLevel      | Profil für Kleinverbrauch - 7 Alarmstufen mit verschiedenen Symbolen und Farbanzeigen
Da wir ein neues Modul machen, kannst du das WAA Prefix auf was neues passendes anpassen.

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/form.json
> +			"name": "LeakInterval",
Passen Leak/Burst auch bei Strom? Ggf. überlegen, ob wir noch was anderes finden?

2022-01-04 14:29 UTC, paresy commented on VerbraucherAlarm/module.php
> +        $this->RegisterVariableBoolean('AlarmAlert', $this->Translate('Alarm Alert'), '~Alert');
Was ist einer Alarm Alert?

Erinnert mich irgendwie daran: 

https://user-images.githubusercontent.com/260376/148073608-a26bffef-f78c-4b26-b3d0-f916384252ee.mp4


 (Bitte entschuldige den schlechten Humor 😄)

2022-01-18 13:04 UTC, Sunnyka98 commented
Änderungen in neuem Repo https://github.com/symcon/VerbrauchsAlarm übertragen

2022-01-18 13:04 UTC, closed without merging